# Generated by Django 5.0.2 on 2024-02-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_texto', models.CharField(max_length=100)),
                ('campo_numero', models.IntegerField()),
                ('campo_fecha', models.DateField()),
            ],
        ),
    ]
