# Generated by Django 5.0.2 on 2024-02-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppResgistro', '0002_delete_mimodelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_registro',
            fields=[
                ('nIdRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('cNombreCompleto', models.TextField()),
                ('cPaisEmpresa', models.TextField()),
                ('cModalidadActividad', models.TextField()),
                ('dFecha', models.DateField()),
                ('tHora', models.TimeField()),
                ('cBrazalete', models.TextField()),
            ],
            options={
                'db_table': 't_regitro',
                'managed': False,
            },
        ),
    ]
