# Generated by Django 5.0.2 on 2024-02-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppResgistro', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='t_registro',
            table='t_registro',
        ),
    ]
