# Generated by Django 5.0.2 on 2024-02-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppResgistro', '0004_alter_t_registro_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='t_registro',
        ),
    ]
