# Generated by Django 5.0.2 on 2024-02-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppResgistro', '0005_delete_t_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_registro',
            fields=[
                ('nIdRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('cNombreCompleto', models.TextField()),
                ('cPaisEmpresa', models.TextField()),
                ('cModalidadActividad', models.TextField()),
                ('dFecha', models.DateField(auto_now_add=True)),
                ('tHora', models.TimeField(auto_now_add=True)),
                ('cBrazalete', models.TextField(null=True)),
            ],
            options={
                'db_table': 't_registro',
                'managed': False,
            },
        ),
    ]
